### ISSUE TITLE
Search is not working.

### ISSUE THREAD

**Issue by aadrian** [clojure/clojurescript-site#10]
Searching for something that is definitely there yields no results.

**Comment by puredanger** [comment]
Correct! Google search had nothing to index till the site was up so it will be a couple days before the site is indexed and search is working as expected. Site map and indexing requests have been submitted, just waiting.

**Comment by rauhs** [comment]
It's still not working. Would the clojurescript site consider algolia docsearch?

https://community.algolia.com/docsearch/

**Comment by puredanger** [comment]
Oops! I broke it this week with the switch to https as the default. I am working on fixing it.
