### ISSUE TITLE
Remove Road Map

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#106]
https://clojurescript.org/community/road-map

It seems like a lot (most?) of the stuff on that page is complete. Perhaps we could simply remove the page.

Having a high level road map to consult might be interesting to the contributor community. If instead we update the page for new dev road map items, perhaps the mention of a 1.0 release could be omitted.

**Comment by swannodette** [comment]
I just removed the page and link, at some future point we might bring something like this back, but I doubt it :)
