### ISSUE TITLE
Section on how to git bisect

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#120]
We have a section on how to report issues https://clojurescript.org/community/reporting-issues and it discusses some somewhat technical details related to trying master.

We might be able to get a little more help from the community by simply documenting how to bisect, especially in the case where a minimal REPL-based repro is known. Here is a rough draft of the kind of content that might be useful:

>Checkout ClojureScript master and cd to the top of the checkout tree.
>
>Assuming you know it is broken on master but worked in 1.9.562, and there is an easy test you can do right in the REPL.
>
>Run these three commands in your shell:
>```
>git bisect start
>git bisect bad HEAD
>git bisect good r1.9.562
>```
>
>Start up the Node REPL using
>
>```
>script/clean && script/bootstrap && rm -rf .cljs_node_repl && script/noderepljs
>```
>
>Try your test in the REPL and then exit the REPL.
>
>If your test succeeded:
>
>```
>git bisect good
>```
>
>Or if your test failed:
>
>```
>git bisect bad
>```
>
>If the bisect is complete, git will incidate that a certain commit hash "is the first bad commit". Copy all of this text for JIRA.
>
>Otherwise go back to the "Start up the Node REPL" step and repeat until done.
>
>When finished, you can do this to restore your git checkout:
>
>```
>git bisect reset
>```

**Comment by mfikes** [comment]
If the above seems desired, I'm willing to put together a PR for a content change.

**Comment by mfikes** [comment]
This is actually a little simpler now that we have the ability to consume ClojureScript as a `:local/root` (you can bisect on the local root while consuming CloureScript in your own project if you want).

**Comment by swannodette** [comment]
Go for it!
