### ISSUE TITLE
Document ^:export

### ISSUE THREAD

**Issue by Deraen** [clojure/clojurescript-site#122]
def `:export` metadata doesn't seem to be mentioned anywhere?

I think it should be mentioned somewhere in reference, and we could also have a simple guide/example about calling Cljs code from JS?

**Comment by swannodette** [comment]
Agreed.

**Comment by LeifAndersen** [comment]
So when googling what `^:export` means in clojurescript, this page comes up. Could we maybe link to the documentation from here (as a comment)?

**Comment by LeifAndersen** [comment]
I guess for future reference this is the link: https://clojurescript.org/reference/advanced-compilation


> For each exported Var, an additional un-renamed alias is established which points to the Closure-munged name. Munged names continue to be used internally within the optimized code.
>
> The ^:export facility is for (and only for) providing external access to Vars via un-renamed aliases. If instead you’d like to debug optimized code which is using shortened names, consider :pseudo-names and :pretty-print, which are described in the following section.
