### ISSUE TITLE
:npm-deps trouble shooting guide

### ISSUE THREAD

**Issue by swannodette** [clojure/clojurescript-site#124]
We should start enumerating various `:npm-deps` issues and how to troubleshoot them. In particular how to determine root causes and what enhancements or changes might be needed to the original JS projects.

**Comment by anmonteiro** [comment]
Not having a `package.json` in the project's directory confuses some versions of NPM

**Comment by rgdelato** [comment]
`npm install` seems to search up the directory structure for a `package.json` file if it doesn't find one in the current directory, so if a `package.json` file exists in a parent directory, that'll cause the NPM dependencies to install in that parent directory instead.

**Comment by swannodette** [comment]
`:npm-deps` has a new role, the old goal is still on the table but I think first things first. Later when people are reliable using bundling, we can start experimenting with the older usage of `:npm-deps`.
