### ISSUE TITLE
Typos in news/2017-07-28-release-candidate

### ISSUE THREAD

**Issue by wodin** [clojure/clojurescript-site#125]
"This features encourages"

"https://http//cljsjs.github.io"

**Comment by swannodette** [comment]
fixed thanks.

**Comment by wodin** [comment]
Hi

The second typo is still there. Firefox mislead me about the exact problem (it removes one of the colons when I hover over the link.)

<img width="564" alt="image" src="https://user-images.githubusercontent.com/4579020/28751479-fbe3d99e-7508-11e7-93bd-529b722cff91.png">
