### ISSUE TITLE
Comunity Forum

### ISSUE THREAD

**Issue by comerc** [clojure/clojurescript-site#14]
Please add forum on https://www.discourse.org/

**Comment by puredanger** [comment]
Hi, we currently have https://groups.google.com/forum/#!forum/clojurescript with other discussion on IRC freenode at #clojurescript and the #clojurescript #cljs-dev channels on Clojurians slack channel. Between all those, we are not eager to add additional discussion forums at this time, but that's something that may change in the future. For now, I'm going to close this ticket as there's nothing we're going to take action on right now. Thanks!
