### ISSUE TITLE
Logo flashes on page change

### ISSUE THREAD

**Issue by coetry** [clojure/clojurescript-site#141]
Every-time new page content is requested, the cljs logo flashes. Can we do some sort of prefetching of content and client side routing to remove the flash? 

Kind of like how https://zeit.co works with Next.js

Please excuse my ignorance as I'm new to a lot of this and trying to keep up with all the advancements in the web space!

**Comment by mfikes** [comment]
Attached shows three frames from a slow motion recording of the flash occurring when changing from the Reference tab to the tools tab. Note the Safari progress indicator in the URL bar and the change in the content below the header bar from Documentation to Running REPLs.
![napkin 08-31-17 8 34 15 am](https://user-images.githubusercontent.com/1723464/29923398-660236a4-8e27-11e7-83a7-2613aa279fb1.png)

**Comment by swannodette** [comment]
I don't see this problem on the site anymore.
