### ISSUE TITLE
Search is not working (500 Internal Server Error)

### ISSUE THREAD

**Issue by xavi** [clojure/clojurescript-site#147]
Any search I try results in empty search results, and in the browser's console I see it's due to a 500 Internal Server Error. For example:

```
GET https://search.clojurescript.org/?q=println 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
m.fn.load @ jquery.min.js:4
(anonymous) @ search?q=println:88
(anonymous) @ search?q=println:89
```

**Comment by puredanger** [comment]
The search functionality for both clojure.org and clojurescript.org are (ultimately) based on Google Site Search, which was recently shut down. I have not yet had a chance to work on a replacement, but until then, the search functionality will probably not do anything good.

**Comment by puredanger** [comment]
Actually, clojure.org's search is still working, so that's probably not the issue (yet).

I would not expect the query you are making to work regardless, as access to search.clojurescript.org is limited to only the clojurescript.org domain to prevent XSS calls.

**Comment by xavi** [comment]
The request and 500 error I posted is what I see in the browser's console when I open this page

https://clojurescript.org/search?q=println

So the search.clojurescript.org request is actually being made from clojurescript.org .

**Comment by puredanger** [comment]
Fixed
