### ISSUE TITLE
ClojureScript ns form guide

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#157]
Considerations around the `ns` are sufficiently complex, where I think a guide page covering it might be useful.

In particular, I think the guide can cover 

* macro inclusion, deriving material from [ClojureScript Macro Sugar](http://blog.fikesfarm.com/posts/2016-03-01-clojurescript-macro-sugar.html)
* `clojure` namespaces aliasing, deriving material from [ClojureScript clojure Namespace Aliasing](http://blog.fikesfarm.com/posts/2016-07-03-clojurescript-clojure-namespace-aliasing.html)

**Comment by swannodette** [comment]
Agreed!

**Comment by mfikes** [comment]
I'll take this on and put together a PR.
