### ISSUE TITLE
Confusion regarding code-splitting

### ISSUE THREAD

**Issue by DjebbZ** [clojure/clojurescript-site#168]
Hello,

The guide about code-splitting says (emphasis mine):
> but this feature only **worked** under `:advanced` compilation [...] All of these issues are now addressed directly in ClojureScript [...] `:optimizations :none`

And the compiler options reference page says (for `:modules`):
> Modules are only supported with `:simple` and `:advanced` optimizations.

It happens that you can still use `:whitespace` and `:none` when developing locally and it would still work. It will respect the split modules and respect the special `:cljs-base` special split, it will just also produce a single javascript file for every ClojureScript/Closure namespace (like it does without code-splitting).

It made me think when developing you had to sacrifice the speed of recompilation to get code-splitting, but it's not the case. Code-splitting code still works in dev with `:none`, it just produces other files than what's specified through `:modules`. In this regard I understand why reference page says it only works in `:simple` and `:advanced` mode, but I find it a bit confusing.

Maybe this needs some rephrasing ?

**Comment by swannodette** [comment]
fixed https://github.com/clojure/clojurescript-site/commit/8affedc604c88dcab75398c1454c390d34df3a7b
