### ISSUE TITLE
Link to Closure Cheatsheet is wrong

### ISSUE THREAD

**Issue by DjebbZ** [clojure/clojurescript-site#170]
Hello,

In https://clojurescript.org/reference/google-closure-library, the link to Closure Cheatsheet leads to a strange ad page. I found this potential replacement in case it's considered good enough http://anton.shevchuk.name/wp-demo/closure-tutorials/cheatsheet.html.

**Comment by zane** [comment]
I ran into this as well. Just to add some detail, the [Closure Cheatsheet](http://www.closurecheatsheet.com/) linked to by [ClojureScript - Google Closure Library](https://clojurescript.org/reference/google-closure-library) now appears to try to fool the viewer into installing malware.

**Comment by swannodette** [comment]
Fixed
