### ISSUE TITLE
New reference and guide pages not listed

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#200]
New reference and page guides not listed in the list that appears on the left.

https://clojurescript.org/guides/ns-forms
https://clojurescript.org/reference/javascript-api

**Comment by mfikes** [comment]
Ahh, this is because this is in the template files. See https://clojurescript.org/community/contributing_site#style

**Comment by swannodette** [comment]
@puredanger looks like we need you to do this. Namespaces is there - but JavaScript API isn't.

**Comment by puredanger** [comment]
will do

**Comment by puredanger** [comment]
fixed

**Comment by swannodette** [comment]
Thanks!

**Comment by puredanger** [comment]
to be more precise - namespaces is there, added JavaScript API, and the Compile Time Type Checking one doesn't seem to exist?

**Comment by swannodette** [comment]
@puredanger we should delete Compile Time Type Checking
