### ISSUE TITLE
Update JavaScript Modules Guide for 1.10.238

### ISSUE THREAD

**Issue by swannodette** [clojure/clojurescript-site#206]

**Comment by henryw374** [comment]
Possibly related to this, (or should be it's own ticket?), is that this page https://clojurescript.org/guides/javascript-modules mentions Dead Code Elimination, yet in my own experiments https://github.com/henryw374/cljs-jsmodules-test I have not been able to achieve this. I also asked on Clojureverse https://clojureverse.org/t/cljs-dead-code-elimination-for-foreign-libraries/5147 and Thomas seems to say it wouldnt work for regular js code. 

If DCE does work for code not written for Closure, it'd be good to have some examples of it (doing it on code from well known npm libs ideally)

**Comment by swannodette** [comment]
I more or less already did this pass.
