### ISSUE TITLE
ClojureScript 'Quick Start' does not metion Clojure version

### ISSUE THREAD

**Issue by leon-vv** [clojure/clojurescript-site#214]
Yesterday I was trying to get ClojureScript to work on my machine. Unfortunately I was using Clojure 1.8 installed using my system package manager. Therefore Clojure did not download and install the ClojureScript dependency mentioned in the deps.edn file. Since the error messages were not helpful and I could not find any other webpage telling me how to get started with ClojureScript this was very frustrating. I finally figured out that my outdated version of Clojure was the problem. Maybe we should put a note on the 'Quick Start' guide to inform people that versions below 1.9 are not supported? 

Thanks for the great project

**Comment by mfikes** [comment]
@leon-vv Are you saying that you had some other (perhaps non-standard) version of `clj` already installed? (I'm trying to understand what steps would repro what you are seeing.)

**Comment by leon-vv** [comment]
Yes, I had version 1.8 installed from my system package manager (apt-get on Debian).
[Link to the package](https://packages.debian.org/buster/clojure)

**Comment by swannodette** [comment]
I just tried a trivial project - Clojure 1.8 works fine. We can't cover all the possible combinations of environments. If it's not working in some evironment - something else must be the problem. https://ask.clojure.org or Slack is probably a better place to field this kind of issue.
