### ISSUE TITLE
google closure cheat sheet link dead & domain-squatted

### ISSUE THREAD

**Issue by jaawerth** [clojure/clojurescript-site#219]
Noticed the link to closurecheatsheet.com URL [linked to here](https://github.com/clojure/clojurescript-site/blob/master/content/reference/google-closure-library.adoc#google-closure-library) is dead and its domain squatted.

I don't know any better cheat-sheets offhand, so I figured I'd just submit an issue and let somebody else handle a PR replacing it with a better one!

**Comment by swannodette** [comment]
fixed in master
