### ISSUE TITLE
use helloworld rather than hello-world or hello_world, avoid jvm classname rules for quickstart

### ISSUE THREAD

**Issue by iambumblehead** [clojure/clojurescript-site#221]
use helloworld rather than hello-world or hello_world, avoid jvm classname rules for quickstart

just now I followed this guide https://clojurescript.org/guides/quick-start and I encountered a problem when I mistakenly named the "hello_world" directory "hello-world". I encountered this error when running the clj command,
```bash
Exception in thread "main" java.lang.IllegalArgumentException: Namespace hello-world.core does not exist
```

additionally, "rlwrap" is not mentioned in the quickstart, but was required for me to run the clj command.

**Comment by mfikes** [comment]
FWIW, master produces a more helpful error message, so perhaps no drastic change is needed in Quick Start:

```
Exception in thread "main" java.lang.IllegalArgumentException: Namespace hello-world.core does not exist. Please check that namespaces with dashes use underscores in the ClojureScript file name.
```

With respect to `rlwrap` being required for `clj`, that is covered here: https://clojure.org/guides/getting_started#_installation_on_linux

**Comment by iambumblehead** [comment]
maybe no changes are needed? perhaps this issue should be closed.
