### ISSUE TITLE
Give examples in `:closure-defines` showing user namspaces

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#268]
The `:closure-defines` compiler option documentation uses `goog.` examples.

Perhaps something like `foo.core/my-var` and `"foo.core.my_var"` as example keys would better illustrate how this can be used for user namespaces.

**Comment by swannodette** [comment]
fixed https://github.com/clojure/clojurescript-site/commit/6e1b9774ae1a7e8dcf19e847719f69c60ae6dced
