### ISSUE TITLE
Broken links on Custom REPLs page

### ISSUE THREAD

**Issue by julianwegkamp** [clojure/clojurescript-site#27]
Two links to the source code on the custom REPLs page (http://clojurescript.org/guides/custom-repls) point to a 404. The urls should contain the revision or the branch for the latest version: https://help.github.com/articles/getting-permanent-links-to-files/

**Comment by puredanger** [comment]
Thanks, PR would be appreciated...

**Comment by julianwegkamp** [comment]
PR #28
