### ISSUE TITLE
Document minimum Clojure version

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#274]
This question doesn't come up very frequently but, if someone wants to know, the minimum version of Clojure required by the ClojureScript compiler doesn't seem to be documented on https://clojurescript.org anywhere.

TBH, there doesn't appear to be an immediately-obvious place to put this information, so if this ticket is addressed, a spot for the info would need to be identified.

Importantly: The minimum version is really dictated by `pom.template.xml`. (Not by other places like ClojureScript's `project.clj` or `script/bootstrap`.)

**Comment by swannodette** [comment]
I'm inclined to say this is probably not necessary? 1.8.0 is what the template says - which is pretty old. Users have to use some dependency tool and they all provide a way to determine this.
