### ISSUE TITLE
Function return type hinting placement

### ISSUE THREAD

**Issue by mfikes** [clojure/clojurescript-site#276]
In the "Differences from Clojure" section on Hinting, we should mention that the hint goes between the `defn` and the function name symbol (whereas in Clojure it is often placed between the function name symbol and the argument vector.

**Comment by vemv** [comment]
I'd much appreciate this one because:

* encountering the issue on my own made me lose time;
* it'd be good to have an official confirmation that the difference is deliberate and 'contractual' (i.e. not WIP)

**Comment by swannodette** [comment]
There's actually no difference here between Clojure & ClojureScript
