### ISSUE TITLE
Add guide about maximizing DCE / minimizing compiled script size

### ISSUE THREAD

**Issue by tomconnors** [clojure/clojurescript-site#290]
There have been a number of discussions on the mailing list and on github about how to make our compiled scripts as small as possible, such as:
- https://groups.google.com/forum/#!searchin/clojurescript/dead$20code%7Csort:relevance/clojurescript/l6_JekFUu6g/F8UiuR08sBYJ
- https://groups.google.com/forum/#!searchin/clojurescript/dead$20code%7Csort:relevance/clojurescript/3QmukS-q9kw/8Tyo0nd8-X4J
- https://groups.google.com/forum/#!searchin/clojurescript/dead$20code%7Csort:relevance/clojurescript/3rL8vKzyJQA/w9_XwpGtBAAJ
- https://groups.google.com/forum/#!topic/clojurescript/4Mfec8_R1Hc

If a guide or reference page on the clojurescript site about this subject would be valuable, I would be happy to write it.

**Comment by swannodette** [comment]
There's just too little benefit and many caveats. Some recommendations are out of date and to be honest that will probably continue to be true whether enhancements are made to Closure Compiler or ClojureScript directly.
