### ISSUE TITLE
Document recommendation: libraries with macros should add self-requires

### ISSUE THREAD

**Issue by borkdude** [clojure/clojurescript-site#303]
Libraries with macros should add self-requires so that users don't have to require macros separately.
It seems like a small wording change away from being descriptive here to becoming prescriptive https://clojurescript.org/guides/ns-forms#_implicit_sugar

**Comment by swannodette** [comment]
fixed https://github.com/clojure/clojurescript-site/commit/cb5cdacc48b6cafbf062a6066856d0f25f6ec41d
