### ISSUE TITLE
A helpful work-around for when the Quick Start doesn't work

### ISSUE THREAD

**Issue by jdjohnston** [clojure/clojurescript-site#304]
At present, the Quick Start using the default browser-based REPL relies on both the shell REPL and the web browser starting together. This doesn't always happen. In fact it currently doesn't work for me on Xubuntu 16.04, something to do with how `clojure.java.shell/sh` launches the browser with `xdg-open`. I plan to submit a ClojureScript JIRA issue later this week.

One work-around for this problem is kludgey & not available for everyone. I can temporarily rename `xdg-open` or move it out of `$PATH`. Not ideal.

A simpler solution that seems worth mentioning in `guides/quick-start.adoc` is to use

 `clj -m cljs.main -ro "{:launch-browser false}" ...`

when there's a problem getting `cljs.main` to automatically launch the browser. This works great for me. The REPL even tells me what URL to use in the browser.

Despite the problems getting started, I'm intrigued to learn more about this variation on Clojure, which has been my favorite Lisp for some time.

**Comment by mfikes** [comment]
Hey @jdjohnston 

Given how vexing this can be if the default browser REPL fails to launch, we actually have what is intended to be a helpful message in the implementation itself to handle this case. See https://github.com/clojure/clojurescript/blob/230e46aee2c9b76e426e85865ab8930c4c26e14f/src/main/clojure/cljs/repl/browser.clj#L346-L353

So, perhaps a fruitful avenue of research / JIRA is to sort out why no exception is thrown or why this message doesn't appear.

**Comment by jdjohnston** [comment]
Hi @mfikes 

Oh, I'm aware of that message. :) I've been poking around in the Clojure code for this problem off & on for about a week. The simple reason the message doesn't appear for me (shouldn't speak for others) is that `clojure.java.shell/sh` *hangs* when it executes `/usr/bin/xdg-open http://localhost:9000...`.

This is a general principle in software engineering (I don't mean to be pedantic here). There are actually *three* possibilities when one calls a function. 1) It will succeed 2) It will fail in some fashion *or* 3) It will simply not return. When `cljs.repl.browser/maybe-browse-url` calls `clojure.java.browse/browse-url` it assumes either 1) or 2). For me, 3) is what happens. I'm almost certain it's an issue with `clojure.java.shell/sh`.

I plan to submit a JIRA issue later this week either with (hopefully) a solution or at least a minimal example to reproduce the problem.

**Comment by jdjohnston** [comment]
Hey @mfikes, the hanging browser REPL will soon be less of an issue. See [CLJ-2493](https://dev.clojure.org/jira/browse/CLJ-2493). Alex Miller said my ticket and approach look OK, so I've signed the CA & am off to format my fix as a patch.

OTOH, I _still_ think a "hand holding" explanation of how to use -ro/--repl-opts with {:launch-browser false} would be a useful addition to the Quick Start page.

**Comment by swannodette** [comment]
fixed https://github.com/clojure/clojurescript-site/commit/63060bfca7c448c58d23911cf350dab7d63d06ce
