### ISSUE TITLE
Making a contribution section stale?

### ISSUE THREAD

**Issue by lread** [clojure/clojurescript-site#307]
Under https://clojurescript.org/community/contributing#_making_a_contribution
1. Is the Clojure Dev Google group still the place to go? Or is the #cljs-dev slack channel more the current meeting place?
   > Before you invest time working on a change, discuss what you’re trying to do with others on the Clojure Dev Google group
2. Links to what seem to be old pages that require logins and then return Page Not Found.
   > Please see the [Contributing](http://dev.clojure.org/display/community/Contributing) wiki for a collection of resources on tickets, builds, patches, source, and more. If you’d like to submit a patch, please follow these guidelines on the [preferred process for submitting](http://dev.clojure.org/display/community/JIRA+workflow).

**Comment by puredanger** [comment]
I have now updated all the links to the old wiki (covers #2).

**Comment by lread** [comment]
That's great, thank you!

**Comment by swannodette** [comment]
I've mentioned the Slack channel as well.
