### ISSUE TITLE
Testing with JavaScript Engines - consider docker image?

### ISSUE THREAD

**Issue by lread** [clojure/clojurescript-site#309]
Under https://clojurescript.org/community/running-tests#testing-javascript-engines, we have quite a bit of manual installation.  Would a docker image work here? Maybe someone in the ClojureScript community already maintains such an image? If so, it would be great to mention such an image and how to take advantage of it on this page.

**Comment by swannodette** [comment]
Not aware of anything, and we definitely don't have time to do something like that ourselves. If somebody makes one feel free to create a PR to update the site.
