### ISSUE TITLE
In Quick-start documentation optimization flag is not in the right place?

### ISSUE THREAD

**Issue by vojkog** [clojure/clojurescript-site#315]
It seems to me that in [quick-start#production-builds](https://clojurescript.org/guides/quick-start#production-builds) optimization flag should be **after** compilation.
This works for me:
`clj -m cljs.main -c hello-world.core --optimization advanced`

**Comment by mfikes** [comment]
@vojkog The flag is spelled `--optimizations` (with an `s` at the end)
