### ISSUE TITLE
are there any plans on supporting deno as a target environment?

### ISSUE THREAD

**Issue by desm** [clojure/clojurescript-site#330]
Hello! Are there any plans to support "deno" as a target environment? Looking at the deno project which was started by Ryan Dahl of Nodejs fame, it looks like deno 1.0 might come out soon (https://github.com/denoland/deno, pinned issue 2473). Cheers!

**Comment by swannodette** [comment]
No plans. Node.js and browsers are our two main targets and I don't see that changing. However nothing is stopping other people giving Deno a try as a target as a library / extension.

**Comment by DavidLiedle** [comment]
Adding my vote for a deno target; I'm aware it's a closed issue, but wanted to speak up. There are dozens of us; dozens!
