### ISSUE TITLE
Very simple stumbling block for ClojureScript QuickStart

### ISSUE THREAD

**Issue by dtonhofer** [clojure/clojurescript-site#336]
At [The ClojureScript QuickStart page][1] we get told to set up a file tree and then run

    clj --main cljs.main --compile hello-world.core --repl

There should be a mention that one has to be in the directory with `deps.edn`. If one is not (for example, one is still in `src`), then:

    Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
    Could not locate cljs/main__init.class, cljs/main.clj or cljs/main.cljc on classpath.

Very confusing!

I urgently suggest to add a line to the Quick Start page saying "make sure you are located in the directory with the `deps.edn` file."

  [1]: https://clojurescript.org/guides/quick-start

**Comment by swannodette** [comment]
PR welcome
