### ISSUE TITLE
QuickStart confuses clj and cljs.main options

### ISSUE THREAD

**Issue by pbwolf** [clojure/clojurescript-site#349]
The QuickStart (https://clojurescript.org/guides/quick-start) confuses clj and cljs.main options, or lures the reader into confusion, in 2 places.

(1) "You can easily explore the options provided by the ClojureScript compiler by using --help. You will see there are abbreviated flags for all the options we used thus far, -m for --main, etc."

This is mistaken.  The --main option used on this page is the clj option, not the identically-named cljs.main option.  

(2) "One important thing to note is that so-called main options like --compile, --main, --repl must always come last."

This puzzled me.  The Quick Start page, as a whole, is a stew of clj and cljs.main in which all 3 of those option words are apparently used, they cannot all be last, and their order matters somewhat.  I did not immediately grasp that the sentence was meant to apply only to the context of cljs.main in isolation, and had nothing to do with the clj --main option that the Quick Start page uses.

----

In my opinion, both of the problematic sentences could be removed.

For (1), abbreviated flags are not necessary to the Quick Start.

For (2), the Quick Start already refers to "clj -m cljs.main --help" and already addresses the crucial matter of clj vs cljs.main options in a paragraph "Let’s look a bit closer at the flags we’ve used here. --main invokes a Clojure function, in this case cljs.main. The cljs.main function supports a variety of command line arguments to specify common tasks..."

**Comment by swannodette** [comment]
@pbwolf thanks for the feedback, 1) is a problem for sure and fixed. 2) is less clear without getting into `clj` in more detail which seems out of the scope for the guide same as say, `java`.
