### ISSUE TITLE
Missing deps.edn in code splitting guide 

### ISSUE THREAD

**Issue by leefurong** [clojure/clojurescript-site#399]
Following [this guide](https://clojurescript.org/guides/code-splitting), I can't make the guide project run via this command:
```
clj -M -m cljs.main -v -co build.edn -c -s
```

Here is the error message:
> xecution error (FileNotFoundException) at clojure.main/main (main.java:40).
> Could not locate cljs/main__init.class, cljs/main.clj or cljs/main.cljc on classpath.
>
> Full report at:
> /var/folders/j_/d8tchqnj7l56qy1m4vcxr1m80000gn/T/clojure-2869212977930894811.edn

After reading the [quick start guide](https://clojurescript.org/guides/quick-start), I added `deps.edn` into the sample project, and the command worked.

So I suggest add `deps.edn` into the [code-splitting-guide](https://clojurescript.org/guides/code-splitting)

**Comment by swannodette** [comment]
fixed https://github.com/clojure/clojurescript-site/commit/0c60e5d6a21fb5cf8f8a60b17f0fa022cc0ec2b2
