### ISSUE TITLE
Sending PRs for a UI tweaks

### ISSUE THREAD

**Issue by kamilogorek** [clojure/clojurescript-site#4]
Hey, just wanted to ask is there a repository where current theme is being hosted?
Right now from what I see it's fetched from Cognitect's CDN and there's no repository for it on clojure org.

Cheers!

**Comment by puredanger** [comment]
The design aspects are not open for PRs - feel free to file an issue here instead.

**Comment by kamilogorek** [comment]
Alright! There you go: https://github.com/clojure/clojurescript-site/issues/5
