### ISSUE TITLE
"Differences" page: Mention struct-maps (defstruct, create-struct)

### ISSUE THREAD

**Issue by pbwolf** [clojure/clojurescript-site#404]
ClojureScript does not appear to have struct-maps (defstruct, create-struct).  

Let's mention this difference on the "Differences from Clojure" page!

Some people feel that struct-maps are obsolete, citing Rich's comment that "most" uses of struct-maps have been overtaken by records.  In any case, struct-maps' absence from ClojureScript should be mentioned: whether it is a woeful fault or a daring breakthrough, it is definitely a difference from Clojure.

**Comment by swannodette** [comment]
Fixed https://github.com/clojure/clojurescript-site/commit/10d889255f6927a2d62c0ebce44ba2675d0a16dd
