### ISSUE TITLE
JAR link at very start of frontpage is broken

### ISSUE THREAD

**Issue by Risord** [clojure/clojurescript-site#407]
JAR link at very start of frontpage is broken:
"[standalone ClojureScript JAR](https://github.com/clojure/clojurescript/releases/download/r1.11.54/cljs.jar)

Or I quess link is correct but there is no r1.11.54 cljs.jar release.

**Comment by swannodette** [comment]
The Quick Start link worked for me? Is this still an issue?

**Comment by puredanger** [comment]
link in the page is 1.11.60 which works, so closing
