### ISSUE TITLE
The 'Auto-aliasing clojure namespaces' paragraph should warn about a potential pitfall related to macros

### ISSUE THREAD

**Issue by moxaj** [clojure/clojurescript-site#46]
The paragraph is at https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#namespaces.

To demonstrate the pitfall, consider the following example:
```
;; foo.cljc
(ns foo
  (:require [clojure.test :as test])
  #?(:cljs (:require-macros [foo])))

(defmacro m [] `(test/deftest ~'x nil))

;; core.cljc
(ns core
  (:require [foo]))

(foo/m)
```

The namespace `foo` compiles perfectly well, `core` however will warn you about the missing `clojure.test` namespace. This places a constraint on `core`, so that it has to explicitly require `clojure.test`, even though it may not use it directly (therefore it is easy to miss).

**Comment by swannodette** [comment]
@moxaj thanks for the feedback!

**Comment by swannodette** [comment]
@moxaj hrm coming back to this, just seems like a bug. Should open an issue in ClojureScript JIRA not here.
