### ISSUE TITLE
Add "Atom" page to "Tools > Editors" section

### ISSUE THREAD

**Issue by rgdelato** [clojure/clojurescript-site#57]
The docs say to create an issue to discuss a new page.

I use Atom in my day-to-day JS work, so I've been using Atom to learn Clojure with the [Parinfer](https://atom.io/packages/parinfer) and [Proto REPL](https://atom.io/packages/proto-repl) plugins installed, and it's been a pretty positive experience. (Though to be fair, I'm pretty new, so there might be obvious things I'm missing.)

Does adding this page seem like a good idea?

**Comment by rgdelato** [comment]
Update: I've also added Atom Linter packages for both joker and kibit:

linter-joker: https://atom.io/packages/linter-joker
linter-kibit: https://atom.io/packages/linter-kibit

**Comment by swannodette** [comment]
@rgdelato go for it!
