### ISSUE TITLE
rlwrap link in quickstart no longer works

### ISSUE THREAD

**Issue by y2kenny** [clojure/clojurescript-site#61]
http://utopia.knoware.nl/~hlub/uck/rlwrap/

http://downforeveryoneorjustme.com/utopia.knoware.nl

I am guessing it supposed to refresh the browser on rebuild?  (rlwrap purpose is unclear to me given that the link is dead.  But I noticed the quick start instruction is not as described unless I refresh the browser.)  Is there a linux equivalent if I am not using OSX?

**Comment by smahood** [comment]
The best link I can find (outside of man pages) seems to be https://github.com/hanslub42/rlwrap

**Comment by swannodette** [comment]
Fixed in master.
