### ISSUE TITLE
Testing page - Info missing when compared to Github Wiki Page

### ISSUE THREAD

**Issue by smahood** [clojure/clojurescript-site#67]
The page at https://clojurescript.org/tools/testing is missing some information that is currently at https://github.com/clojure/clojurescript/wiki/Testing

Likely worth a PR to get it caught up.

**Comment by swannodette** [comment]
@smahood please!

**Comment by alex-dixon** [comment]
Ready to close?

**Comment by swannodette** [comment]
Sorry for the long delay and thanks.
