### ISSUE TITLE
Unable to download theme assets

### ISSUE THREAD

**Issue by statonjr** [clojure/clojurescript-site#78]
What I did:

Followed the instructions to download the theme assets for the site so that I could build and preview changes locally: https://github.com/clojure/clojurescript-site/blob/master/content/community/contributing_site.adoc#build

I clicked on the link to the ZIP file (http://cdn.cognitect.com/clojurescript.org/clojuretheme.zip) to download the theme assets. 

What happened:

I received a 404  Not Found error. I also tried `curl` and saw the same response. I tried HTTPS, but the operation timed out.

What I expected to happen:

I expected to receive a ZIP file with the theme assets.

**Comment by puredanger** [comment]
We might never have uploaded it! I can take care of this.

**Comment by puredanger** [comment]
Actually, we did upload it, but the link was wrong. Should be http://cdn.cognitect.com/clojurescript.org/cljstheme.zip. I'll fix in the site.

**Comment by puredanger** [comment]
Fixed in d30e08e56
