### ISSUE TITLE
A "News" section is missing!

### ISSUE THREAD

**Issue by aadrian** [clojure/clojurescript-site#8]
A "News" section is missing. At least from the top menu. 
IMHO even if there's none so far, it could be linked to the clojure.org news page at least.

**Comment by puredanger** [comment]
We decided that it didn't make sense to have this yet. We may add it later.

**Comment by shaunlebron** [comment]
@puredanger would you take a PR to merge the mailing list posts as a news page? http://cljs.github.io/news/

**Comment by swannodette** [comment]
Done!
