### ISSUE TITLE
Logo styling issues

### ISSUE THREAD

**Issue by shaunlebron** [clojure/clojurescript-site#81]
The logo is not vertically centered in the header bar (creating visual tension!):

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td valign=top>
<img width="314" alt="screen shot 2017-06-01 at 12 36 01 pm" src="https://cloud.githubusercontent.com/assets/116838/26693300/4f162e50-46c9-11e7-9ecc-100bfd69d707.png">
</td>
<td valign=top>
<img width="313" alt="screen shot 2017-06-01 at 12 35 35 pm" src="https://cloud.githubusercontent.com/assets/116838/26693307/54e8e2b4-46c9-11e7-80ad-b4324e373da2.png">
</td>
</tr>
</table>

And the logo does not blend properly with the footer background:

<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td valign=top>
<img src="https://cloud.githubusercontent.com/assets/116838/26693661/99983cc4-46ca-11e7-9e41-2fbb996afabc.png">
</td>
<td valign=top>
<img src="https://cloud.githubusercontent.com/assets/116838/26693673/a03a3abe-46ca-11e7-9136-783c8baf0cee.png">
</td>
</tr>
</table>

**Comment by swannodette** [comment]
@shaunlebron thanks I'll try to find some time to take a look at this

**Comment by swannodette** [comment]
Haven't forgotten :)

**Comment by swannodette** [comment]
These styling fixes have been applied. @shaunlebron please check when you have time.

**Comment by shaunlebron** [comment]
Looks great, thanks!
