### ISSUE TITLE
site is slow

### ISSUE THREAD

**Issue by jiyinyiyong** [clojure/clojurescript-site#82]
* no long term caching, a lot of 304 requests
* some of JavaScript is not minified(webflow.js)
* too many requests for CSS
* TTFB show 150ms+(maybe my network slow?)
* page blinks(?) probably due to web fonts issue

![image](https://user-images.githubusercontent.com/449224/26917227-0d7ae11e-4bf3-11e7-82f2-30aaec85227c.png)
![image](https://user-images.githubusercontent.com/449224/26917243-1a4c6ec6-4bf3-11e7-915c-94ffdea34095.png)

**Comment by swannodette** [comment]
I don't really think this is slow enough to open an issue, sorry.

**Comment by jiyinyiyong** [comment]
Well, it's your decision to make. But seeing from my side as a ClojureScript user for years, it sometimes hurts when it takes long time to access official docs and it's not a good example for us users when ClojureScript comes with a slow official site.

**Comment by puredanger** [comment]
I saw this go by and I made a few updates on fonts, css, caching, logo. Still more that could be done, but that helped a little. Made same changes to clojure.org.
