### ISSUE TITLE
Create :modules code-splitting guide

### ISSUE THREAD

**Issue by swannodette** [clojure/clojurescript-site#85]
Moved over from https://dev.clojure.org/jira/browse/CLJS-1129

**Comment by swannodette** [comment]
Enhanced `:modules` support landed in master. We can use https://gist.github.com/swannodette/6150d4213aeb9eba31e03ae522af4425 as a starting point for a guide.

As mentioned by @anmonteiro we should probably mention a couple of advanced non-obvious things (vendorization, shared module inference), and as another user discovered we should call that patterns around manual `:modules` management should be avoided.

**Comment by swannodette** [comment]
fixed in master

**Comment by anmonteiro** [comment]
Where is this fixed? Did you include anything about vendorization and shared module inference as per your comment above?

**Comment by swannodette** [comment]
@anmonteiro well there's guide :) I agree it should be extended, but we can make another issue for that.
