### ISSUE TITLE
Request for an "Official ClojureScript Guide"

### ISSUE THREAD

**Issue by jiyinyiyong** [clojure/clojurescript-site#87]
Previous conversation: https://twitter.com/jiyinyiyong/status/877826188072239105

See that Google says:
![image](https://user-images.githubusercontent.com/449224/27428386-74ee2936-5707-11e7-852a-a6fd54304ed9.png)

When beginners search for a guide, modern-cljs is the only guide they find on first screen.

**Comment by mfikes** [comment]
In the Twitter conversation, it seemed to indicate the scope is with respect to macros
```
"Official ClojureScript Guide" covering the way to create macros.
```

Perhaps this is useful (it covers the concepts surrounding ClojureScript macros): https://clojurescript.org/about/differences#_macros

And this, which includes details on the `ns` form with ClojureScript macros: https://clojurescript.org/about/differences#_namespaces

**Comment by jiyinyiyong** [comment]
That indicates the fact people always need to learn and run Clojure first, then he can start learning ClojureScript. I think it's not the case for many of us, coming to Clojure from React and ClojureScript. And the guide for ClojureScript is not as easy to follow.

**Comment by swannodette** [comment]
Duplicating information already well covered by Clojure is just not a practical way for the maintainers to spend their time. We enough to do documenting all the things that are unique to ClojureScript. Sorry.
